coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 70%
        informational: true

comment:
  layout: "reach, diff, flags, files"
  require_changes: true

ignore:
  - "src/**/Migrations/**"
  - "tests/**"
