// <auto-generated />
using System;
using AudioYotoShelf.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AudioYotoShelf.Infrastructure.Migrations
{
    [DbContext(typeof(AudioYotoShelfDbContext))]
    partial class AudioYotoShelfDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AudioYotoShelf.Core.Entities.CardTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AbsLibraryItemId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("AgeSuggestionReason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("AgeSuggestionSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("BookAuthor")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<int?>("OverrideMaxAge")
                        .HasColumnType("integer");

                    b.Property<int?>("OverrideMinAge")
                        .HasColumnType("integer");

                    b.Property<string>("PlaybackType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer");

                    b.Property<string>("SeriesName")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<float?>("SeriesSequence")
                        .HasColumnType("real");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SuggestedMaxAge")
                        .HasColumnType("integer");

                    b.Property<int>("SuggestedMinAge")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("YotoCardId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("AbsLibraryItemId");

                    b.HasIndex("YotoCardId");

                    b.HasIndex("UserConnectionId", "Status");

                    b.ToTable("CardTransfers");
                });

            modelBuilder.Entity("AudioYotoShelf.Core.Entities.GeneratedIcon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ContextTitle")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("IconData")
                        .HasColumnType("bytea");

                    b.Property<bool>("IsBookCover")
                        .HasColumnType("boolean");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("PublicIconId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("TimesUsed")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("YotoIconUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("YotoMediaId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("UserConnectionId");

                    b.ToTable("GeneratedIcons");
                });

            modelBuilder.Entity("AudioYotoShelf.Core.Entities.TrackMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AbsFileIno")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("CardTransferId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChapterIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ChapterTitle")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("EndTime")
                        .HasColumnType("double precision");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("GeneratedIconId")
                        .HasColumnType("uuid");

                    b.Property<double>("StartTime")
                        .HasColumnType("double precision");

                    b.Property<double?>("TranscodedDuration")
                        .HasColumnType("double precision");

                    b.Property<long?>("TranscodedFileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YotoTrackUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("YotoTranscodedSha256")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("YotoUploadId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CardTransferId");

                    b.HasIndex("GeneratedIconId");

                    b.HasIndex("YotoTranscodedSha256");

                    b.ToTable("TrackMappings");
                });

            modelBuilder.Entity("AudioYotoShelf.Core.Entities.UserConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudiobookshelfToken")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<DateTimeOffset?>("AudiobookshelfTokenValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AudiobookshelfUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultLibraryId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("DefaultMaxAge")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultMinAge")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("YotoAccessToken")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("YotoDeviceCode")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("YotoRefreshToken")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<DateTimeOffset?>("YotoTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserConnections");
                });

            modelBuilder.Entity("AudioYotoShelf.Core.Entities.CardTransfer", b =>
                {
                    b.HasOne("AudioYotoShelf.Core.Entities.UserConnection", "UserConnection")
                        .WithMany("CardTransfers")
                        .HasForeignKey("UserConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserConnection");
                });

            modelBuilder.Entity("AudioYotoShelf.Core.Entities.GeneratedIcon", b =>
                {
                    b.HasOne("AudioYotoShelf.Core.Entities.UserConnection", "UserConnection")
                        .WithMany("GeneratedIcons")
                        .HasForeignKey("UserConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserConnection");
                });

            modelBuilder.Entity("AudioYotoShelf.Core.Entities.TrackMapping", b =>
                {
                    b.HasOne("AudioYotoShelf.Core.Entities.CardTransfer", "CardTransfer")
                        .WithMany("TrackMappings")
                        .HasForeignKey("CardTransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AudioYotoShelf.Core.Entities.GeneratedIcon", "GeneratedIcon")
                        .WithMany()
                        .HasForeignKey("GeneratedIconId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CardTransfer");

                    b.Navigation("GeneratedIcon");
                });

            modelBuilder.Entity("AudioYotoShelf.Core.Entities.CardTransfer", b =>
                {
                    b.Navigation("TrackMappings");
                });

            modelBuilder.Entity("AudioYotoShelf.Core.Entities.UserConnection", b =>
                {
                    b.Navigation("CardTransfers");

                    b.Navigation("GeneratedIcons");
                });
#pragma warning restore 612, 618
        }
    }
}
